# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-25 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_filename', models.ImageField(upload_to='')),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(help_text='Please enter an integer as months lived.')),
                ('gender', models.CharField(help_text="Enter 'm' for male, 'f' for female or 'u' for unknown", max_length=1)),
                ('size', models.CharField(help_text="All size options are 's,m,l,xl,u' for small, medium, large, extra large and unknown", max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='u', help_text="All status options are 'l,d,u' for liked, disliked, and undecided.", max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='b,y,a,s', help_text="All age options are 'b,y,a,s' for baby, young, adult and senior", max_length=7)),
                ('gender', models.CharField(default='m,f', help_text="All gender options are 'm,f' for male and female", max_length=3)),
                ('size', models.CharField(default='s,m,l,xl', help_text="All size options are 's,m,l,xl' for small, medium, large, and extra large", max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
