# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(help_text="Enter 'm' for male, 'f' for female", max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(help_text="All size options are 's,m,l,xl' for small, medium, large or extra large", max_length=2),
        ),
    ]
