# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', help_text="All age options are 'b,y,a,s' for baby, young, adult and senior", max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f', help_text="All gender options are 'm,f' for male and female", max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', help_text="All size options are 's,m,l,xl' for small, medium, large, and extra large", max_length=8),
        ),
    ]
