# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20180416_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
