# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-17 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20180416_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='unknown breed', max_length=100),
        ),
    ]
